# Generated by Django 3.1.7 on 2021-09-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['message']},
        ),
    ]
