# Generated by Django 3.1.7 on 2021-09-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20210930_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(default='')),
                ('password', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
