# Generated by Django 3.1.7 on 2021-09-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20210930_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
                ('email', models.TextField(default='')),
                ('password', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='CheckLogin',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
    ]
